//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 9/2/2010 12:40:03 PM
namespace ElmcityUtils
{
    
    /// <summary>
    /// There are no comments for elmcity_log_entry_entities in the schema.
    /// </summary>
    public partial class elmcity_log_entry_entities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new elmcity_log_entry_entities object using the connection string found in the 'elmcity_log_entry_entities' section of the application configuration file.
        /// </summary>
        public elmcity_log_entry_entities() : 
                base("name=elmcity_log_entry_entities", "elmcity_log_entry_entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new elmcity_log_entry_entities object.
        /// </summary>
        public elmcity_log_entry_entities(string connectionString) : 
                base(connectionString, "elmcity_log_entry_entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new elmcity_log_entry_entities object.
        /// </summary>
        public elmcity_log_entry_entities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "elmcity_log_entry_entities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for elmcity_log_entry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<elmcity_log_entry> elmcity_log_entry
        {
            get
            {
                if ((this._elmcity_log_entry == null))
                {
                    this._elmcity_log_entry = base.CreateQuery<elmcity_log_entry>("[elmcity_log_entry]");
                }
                return this._elmcity_log_entry;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<elmcity_log_entry> _elmcity_log_entry;
        /// <summary>
        /// There are no comments for elmcity_log_entry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToelmcity_log_entry(elmcity_log_entry elmcity_log_entry)
        {
            base.AddObject("elmcity_log_entry", elmcity_log_entry);
        }
    }
    /// <summary>
    /// There are no comments for elmcity_log_entry.elmcity_log_entry in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ticks
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="elmcity_log_entry", Name="elmcity_log_entry")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class elmcity_log_entry : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new elmcity_log_entry object.
        /// </summary>
        /// <param name="datetime">Initial value of datetime.</param>
        /// <param name="ticks">Initial value of ticks.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static elmcity_log_entry Createelmcity_log_entry(global::System.DateTime datetime, long ticks)
        {
            elmcity_log_entry elmcity_log_entry = new elmcity_log_entry();
            elmcity_log_entry.datetime = datetime;
            elmcity_log_entry.ticks = ticks;
            return elmcity_log_entry;
        }
        /// <summary>
        /// There are no comments for property datetime in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime datetime
        {
            get
            {
                return this._datetime;
            }
            set
            {
                this.OndatetimeChanging(value);
                this.ReportPropertyChanging("datetime");
                this._datetime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("datetime");
                this.OndatetimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _datetime;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndatetimeChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndatetimeChanged();
        /// <summary>
        /// There are no comments for property type in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string type
        {
            get
            {
                return this._type;
            }
            set
            {
                this.OntypeChanging(value);
                this.ReportPropertyChanging("type");
                this._type = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("type");
                this.OntypeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _type;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OntypeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OntypeChanged();
        /// <summary>
        /// There are no comments for property message in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string message
        {
            get
            {
                return this._message;
            }
            set
            {
                this.OnmessageChanging(value);
                this.ReportPropertyChanging("message");
                this._message = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("message");
                this.OnmessageChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _message;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmessageChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmessageChanged();
        /// <summary>
        /// There are no comments for property data in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string data
        {
            get
            {
                return this._data;
            }
            set
            {
                this.OndataChanging(value);
                this.ReportPropertyChanging("data");
                this._data = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("data");
                this.OndataChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _data;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndataChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndataChanged();
        /// <summary>
        /// There are no comments for property ticks in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long ticks
        {
            get
            {
                return this._ticks;
            }
            set
            {
                this.OnticksChanging(value);
                this.ReportPropertyChanging("ticks");
                this._ticks = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ticks");
                this.OnticksChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _ticks;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnticksChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnticksChanged();
    }
}
