//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ElmcityUtils
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class elmcity_log_entry_entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new elmcity_log_entry_entities object using the connection string found in the 'elmcity_log_entry_entities' section of the application configuration file.
        /// </summary>
        public elmcity_log_entry_entities() : base("name=elmcity_log_entry_entities", "elmcity_log_entry_entities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new elmcity_log_entry_entities object.
        /// </summary>
        public elmcity_log_entry_entities(string connectionString) : base(connectionString, "elmcity_log_entry_entities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new elmcity_log_entry_entities object.
        /// </summary>
        public elmcity_log_entry_entities(EntityConnection connection) : base(connection, "elmcity_log_entry_entities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<elmcity_log_entry> elmcity_log_entry
        {
            get
            {
                if ((_elmcity_log_entry == null))
                {
                    _elmcity_log_entry = base.CreateObjectSet<elmcity_log_entry>("elmcity_log_entry");
                }
                return _elmcity_log_entry;
            }
        }
        private ObjectSet<elmcity_log_entry> _elmcity_log_entry;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the elmcity_log_entry EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToelmcity_log_entry(elmcity_log_entry elmcity_log_entry)
        {
            base.AddObject("elmcity_log_entry", elmcity_log_entry);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="elmcity_log_entry", Name="elmcity_log_entry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class elmcity_log_entry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new elmcity_log_entry object.
        /// </summary>
        /// <param name="datetime">Initial value of the datetime property.</param>
        /// <param name="ticks">Initial value of the ticks property.</param>
        public static elmcity_log_entry Createelmcity_log_entry(global::System.DateTime datetime, global::System.Int64 ticks)
        {
            elmcity_log_entry elmcity_log_entry = new elmcity_log_entry();
            elmcity_log_entry.datetime = datetime;
            elmcity_log_entry.ticks = ticks;
            return elmcity_log_entry;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime datetime
        {
            get
            {
                return _datetime;
            }
            set
            {
                OndatetimeChanging(value);
                ReportPropertyChanging("datetime");
                _datetime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("datetime");
                OndatetimeChanged();
            }
        }
        private global::System.DateTime _datetime;
        partial void OndatetimeChanging(global::System.DateTime value);
        partial void OndatetimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String message
        {
            get
            {
                return _message;
            }
            set
            {
                OnmessageChanging(value);
                ReportPropertyChanging("message");
                _message = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("message");
                OnmessageChanged();
            }
        }
        private global::System.String _message;
        partial void OnmessageChanging(global::System.String value);
        partial void OnmessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String data
        {
            get
            {
                return _data;
            }
            set
            {
                OndataChanging(value);
                ReportPropertyChanging("data");
                _data = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("data");
                OndataChanged();
            }
        }
        private global::System.String _data;
        partial void OndataChanging(global::System.String value);
        partial void OndataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ticks
        {
            get
            {
                return _ticks;
            }
            set
            {
                if (_ticks != value)
                {
                    OnticksChanging(value);
                    ReportPropertyChanging("ticks");
                    _ticks = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ticks");
                    OnticksChanged();
                }
            }
        }
        private global::System.Int64 _ticks;
        partial void OnticksChanging(global::System.Int64 value);
        partial void OnticksChanged();

        #endregion
    
    }

    #endregion
    
}
