//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ElmcityUtils
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class iis_failed_request_entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new iis_failed_request_entities object using the connection string found in the 'iis_failed_request_entities' section of the application configuration file.
        /// </summary>
        public iis_failed_request_entities() : base("name=iis_failed_request_entities", "iis_failed_request_entities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new iis_failed_request_entities object.
        /// </summary>
        public iis_failed_request_entities(string connectionString) : base(connectionString, "iis_failed_request_entities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new iis_failed_request_entities object.
        /// </summary>
        public iis_failed_request_entities(EntityConnection connection) : base(connection, "iis_failed_request_entities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<iis_failed_request> iis_failed_request
        {
            get
            {
                if ((_iis_failed_request == null))
                {
                    _iis_failed_request = base.CreateObjectSet<iis_failed_request>("iis_failed_request");
                }
                return _iis_failed_request;
            }
        }
        private ObjectSet<iis_failed_request> _iis_failed_request;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the iis_failed_request EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToiis_failed_request(iis_failed_request iis_failed_request)
        {
            base.AddObject("iis_failed_request", iis_failed_request);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="iis_failed_request", Name="iis_failed_request")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class iis_failed_request : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new iis_failed_request object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="url">Initial value of the url property.</param>
        /// <param name="duration">Initial value of the duration property.</param>
        /// <param name="created">Initial value of the created property.</param>
        /// <param name="computer">Initial value of the computer property.</param>
        /// <param name="status">Initial value of the status property.</param>
        public static iis_failed_request Createiis_failed_request(global::System.Int32 id, global::System.String url, global::System.Int32 duration, global::System.DateTime created, global::System.String computer, global::System.String status)
        {
            iis_failed_request iis_failed_request = new iis_failed_request();
            iis_failed_request.ID = id;
            iis_failed_request.url = url;
            iis_failed_request.duration = duration;
            iis_failed_request.created = created;
            iis_failed_request.computer = computer;
            iis_failed_request.status = status;
            return iis_failed_request;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reason
        {
            get
            {
                return _reason;
            }
            set
            {
                OnreasonChanging(value);
                ReportPropertyChanging("reason");
                _reason = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("reason");
                OnreasonChanged();
            }
        }
        private global::System.String _reason;
        partial void OnreasonChanging(global::System.String value);
        partial void OnreasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 duration
        {
            get
            {
                return _duration;
            }
            set
            {
                OndurationChanging(value);
                ReportPropertyChanging("duration");
                _duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("duration");
                OndurationChanged();
            }
        }
        private global::System.Int32 _duration;
        partial void OndurationChanging(global::System.Int32 value);
        partial void OndurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created
        {
            get
            {
                return _created;
            }
            set
            {
                OncreatedChanging(value);
                ReportPropertyChanging("created");
                _created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created");
                OncreatedChanged();
            }
        }
        private global::System.DateTime _created;
        partial void OncreatedChanging(global::System.DateTime value);
        partial void OncreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String computer
        {
            get
            {
                return _computer;
            }
            set
            {
                OncomputerChanging(value);
                ReportPropertyChanging("computer");
                _computer = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("computer");
                OncomputerChanged();
            }
        }
        private global::System.String _computer;
        partial void OncomputerChanging(global::System.String value);
        partial void OncomputerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();

        #endregion
    
    }

    #endregion
    
}
